-- MySQL Script generated by MySQL Workbench
-- lun 25 may 2020 21:51:39 -05
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema Delilah_Resto
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Delilah_Resto
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Delilah_Resto` DEFAULT CHARACTER SET latin1 ;
USE `Delilah_Resto` ;

-- -----------------------------------------------------
-- Table `Delilah_Resto`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Delilah_Resto`.`usuarios` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NULL DEFAULT NULL,
  `apellido` VARCHAR(255) NULL DEFAULT NULL,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  `telefono` VARCHAR(255) NULL DEFAULT NULL,
  `direccioEnvio` VARCHAR(255) NULL DEFAULT NULL,
  `nombreUsuario` VARCHAR(255) NULL DEFAULT NULL,
  `password` VARCHAR(255) NULL DEFAULT NULL,
  `rol` VARCHAR(255) NULL DEFAULT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `Delilah_Resto`.`pedidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Delilah_Resto`.`pedidos` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `fecha` DATETIME NULL DEFAULT NULL,
  `tipo_pago` VARCHAR(255) NULL DEFAULT NULL,
  `estado` VARCHAR(255) NULL DEFAULT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  `usuarioId` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `usuarioId` (`usuarioId` ASC),
  CONSTRAINT `pedidos_ibfk_1`
    FOREIGN KEY (`usuarioId`)
    REFERENCES `Delilah_Resto`.`usuarios` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `Delilah_Resto`.`productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Delilah_Resto`.`productos` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nombreProducto` VARCHAR(255) NULL DEFAULT NULL,
  `imagen` VARCHAR(255) NULL DEFAULT NULL,
  `precio` INT(11) NULL DEFAULT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `Delilah_Resto`.`pedidos_productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Delilah_Resto`.`pedidos_productos` (
  `cantidad` INT(11) NULL DEFAULT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  `pedidoId` INT(11) NOT NULL,
  `productoId` INT(11) NOT NULL,
  PRIMARY KEY (`pedidoId`, `productoId`),
  INDEX `productoId` (`productoId` ASC),
  CONSTRAINT `pedidos_productos_ibfk_1`
    FOREIGN KEY (`pedidoId`)
    REFERENCES `Delilah_Resto`.`pedidos` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `pedidos_productos_ibfk_2`
    FOREIGN KEY (`productoId`)
    REFERENCES `Delilah_Resto`.`productos` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;